name: parkcontrol
description: "ParkControl: gestión profesional de estacionamientos."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  http: ^1.6.0
  url_launcher: ^6.3.2

  # PDF
  pdf: 3.12.0
  printing: 5.14.3

  # Excel
  excel: 4.0.6

  # Compartir archivos
  share_plus: ^13.3.0

  # SQLite local multiplataforma para la cola offline.
  drift: ^2.34.3
  drift_flutter: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  drift_dev: ^2.34.5
  sqlite3: ^3.5.1

flutter:
  uses-material-design: true
